# Generated by Django 5.2.2 on 2025-06-23 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moodentry",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Mood Entry",
                "verbose_name_plural": "Mood Entries",
            },
        ),
        migrations.AddField(
            model_name="moodentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the entry was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moodentry",
            name="title",
            field=models.CharField(
                blank=True, help_text="Optional title for your entry", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="date",
            field=models.DateField(
                auto_now_add=True, help_text="Date of the mood entry"
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("anxious", "Anxious"),
                    ("excited", "Excited"),
                    ("neutral", "Neutral"),
                ],
                help_text="Select your mood",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about your mood", null=True
            ),
        ),
    ]
